server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:      
        - id: user-general
          uri: lb://msvc-user
          predicates:
            - Path=/api/user/**
        
        - id: user-auth
          uri: lb://msvc-user
          predicates:
            - Path=/api/auth/**
    
        - id: shops
          uri: lb://msvc-shops
          predicates:
            - Path=/api/shop/**
        
        - id: appointments
          uri: lb://msvc-appointments
          predicates:
            - Path=/api/appointment/**
        - id: payments
          uri: lb://msvc-payments
          predicates:
            - Path=/api/payment/**    
            
      default-filters:  # TODO OK, YA FUNCIONA TAMBIEN EL GATEWAY!
        - name: PreserveHostHeader