server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:      
        - id: user
          uri: http://localhost:8001
          predicates:
            - Path=/api/user/**

        - id: security
          uri: lb://msvc-security
          predicates:
            - Path=/api/auth/**    
        - id: shops
          uri: lb://msvc-shops
          predicates:
            - Path=/api/shop/**
          filters:
            - name: RequestHeader
              args:
                name: Authorization
                value: "#{request.headers['Authorization']}" #Esto nos va a dejar mandar el Jwt mediante el gateway desde users#